stages:
  preprocess:
    cmd: python preprocess.py
    deps:
    - data/raw_data.csv
    outs:
    - data/preprocessed_data.csv

  train_model:
    cmd: python train.py
    deps:
    - data/my_dataset.csv
    - train.py
    outs:
    - model.pkl
  tune_model:
    cmd: python train_tune.py
    deps:
    - data/preprocessed_data.csv
    - train_tune.py
    outs:
    - best_model.pkl
